Fixes from code review
collinsugwu/Apple-clone pull request #2
Opened 2019-09-28 11:35 UTC by collinsugwu

what this PR does
1 use html semantics
2 add search bar to input
3 adjust the nav bar

2019-09-28 15:04 UTC, Ispirett requested changes
Great Job @collinsugwu  you did excellent work with this project and changes. :+1: :100: 

**Some changes to make are below**

Please add the the the`<meta charset="UTF-8">

Submit for rereview when finished

2019-09-28 15:04 UTC, Ispirett commented on index.html
> +                        <img src="resources/img/iphone5s.jpg" alt="iPhone5s">
These images are actually links so they should be wrapped in `<a>` tags

2019-09-29 19:38 UTC, whiz25 commented on resources/css/main.css
>  .header {
Your ```nav``` doesn't quite have the ```gradient``` styling which is the main objective of this project. Try adding ```background: -webkit-gradient(linear, 0 0, 0 100%, from(rgba(0, 0, 0, .2)), color-stop(0.05, rgba(0, 0, 0, 0)), color-stop(0.97, rgba(0, 0, 0, 0)), to(rgba(0, 0, 0, .45))), -webkit-gradient(linear, 0 0, 100% 0, from(rgba(0, 0, 0, .2)), color-stop(0.002, rgba(0, 0, 0, 0)), color-stop(0.998, rgba(0, 0, 0, 0)), to(rgba(0, 0, 0, .2)))``` styling to the background of your ```nav```.

2019-09-29 19:48 UTC, whiz25 requested changes
## Good job :+1: @collinsugwu 
This project is almost complete. But it requires some changes to be made.
- [ ] Style the ```navbar``` background using ```gradient``` just like the original site. Please see my comment.

## [NEXT PROJECT]
- [ ] Please follow the [github flow](https://guides.github.com/introduction/flow/) in your next projects.

Make those changes and send for another review.

2019-09-30 18:27 UTC, wathigo approved these changes
### Great work Guys :clap: 
**You may move on :)**
_Good luck in your future projects_

2019-09-30 18:35 UTC, merged